### ISSUE TITLE
KeyError `players`

### ISSUE THREAD

**Issue by molanp** [FragLand/minestat#216]
### How to Reproduce Behavior/Symptoms
* When there is no player list in the returned information.

### MineStat Version
* 2.6.2

### Programming Language and Compiler/Interpreter Version
* Python 3.11

### Operating System
* Linux

### Output/Screenshot(s)

```
MineStat Version 2.6.2
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 5, in <module>
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/minestat/__init__.py", line 317, in __init__
    self.json_query()
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/minestat/__init__.py", line 776, in json_query
    return self.__parse_json_payload(payload_raw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/minestat/__init__.py", line 800, in __parse_json_payload
    self.max_players = payload_obj["players"]["max"]
                       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'players'
```

**Comment by molanp** [comment]
Test ip is `mc.bilicraft.com`

**Comment by mindsolve** [comment]
Hi molanp,
We were under the assumption that the "player" object in the JSON SLP response was required, so the library doesn't currently handle it being missing.

This is how it looks in the official Minecraft client:
![grafik](https://github.com/FragLand/minestat/assets/24863329/eeaee1e1-70bf-4151-a0ce-e0f5ca112045)

@ldilley: If the official clients supports (or at least gracefully handles) this, we should probably too, right?

For reference, here is the full SLP JSON:
```json
{
   "version":{
      "name":"Waterfall 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17.x, 1.18.x, 1.19.x, 1.20.x",
      "protocol":-1
   },
   "description":{
      "extra":[
         {
            "extra":[
               {
                  "color":"white",
                  "extra":[
                     {
                        "color":"aqua",
                        "extra":[
                           {
                              "color":"dark_red",
                              "extra":[
                                 {
                                    "color":"white",
                                    "text":" \\u003c\\u003d\\u003d\\u003d\\u003d\\u003d"
                                 }
                              ],
                              "text":"17th"
                           }
                        ],
                        "text":"Bilicraft "
                     }
                  ],
                  "text":"\\u003d\\u003d\\u003d\\u003d\\u003d\\u003e "
               }
            ],
            "text":"            "
         },
         {
            "text":"\\n"
         },
         {
            "extra":[
               {
                  "color":"green",
                  "extra":[
                     {
                        "color":"white",
                        "extra":[
                           {
                              "color":"yellow",
                              "extra":[
                                 {
                                    "color":"white",
                                    "extra":[
                                       {
                                          "color":"aqua",
                                          "text":"mc.bilicraft.com"
                                       }
                                    ],
                                    "text":"◇ "
                                 }
                              ],
                              "text":"正版验证，无需白名单 "
                           }
                        ],
                        "text":"◇ "
                     }
                  ],
                  "text":"1.20.1 "
               }
            ],
            "text":"         "
         }
      ],
      "text":""
   },
   "favicon":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAhGklEQVR4Xq17Z3NUV7cmd+58uFP11tT9B1NTNVXz5U5dY2OCMSaapCyUc44oCyQhchIZTLAAE40Bg8km55yMASGUWqFzzjlJembtc6TuPsIC/NZ9qnZ1n9C7e629wrPW2T1mzF8AE8O/oHGDhnlwYnj/wMQw9E8Ig5+GL2SwY/+EcO69lxvhcI8fHhFDIzJkRMHFjeihETM0YuHkxgJuuCbEwc2NeBqJdJwAJ71yY2ISXJOS4ZxM49sUOL+jMS0VzulpcMxMg3NWBpyzM+Camwn3vKx+d3iO2R2Zc9MTlfvFSDk/AAn8bzQe0QAJDiY4E9I7JRresqXwHf4V/U9fof/JS7irV5JAYfA0bID/95vwXboJ71+OW6OM24LhCYw78Jy5DsvXC2CblQX/o1fw3XxC99zlhuv4JZgmJsJR3QT/szfwXrkP79X7sC3eAPOcTPgevIA9ZzHspADb/EzYw7LgiMyGKyoH7ti8x564/H8DMIaNkcL/LxrGYcHZinu/I8E3/4j+1k4EMDAAx/Z9sIRnwDIpHP4/3wWv/RfCef4mtLSqzrM3Rl6CYckWaGakAYODwXPVa2H94RB3zjCPBG8+BveFGzCnlcEckQVbdA6csblwxecb3QkF/xuhCiDB/0HDFrrqvob1GDSYgt9KcN15BOWXs6CLyoTn0Qvop8bA8/gPwT3/lbCREuRfxcCwaNPIS1DElUI2Oz1wrIzJh/3CTajmpUNXvjzkTvrd1+7BSMJbaTji8+BKKrC5kwv/EaqAe8PCc7594LhgAgbj5j2QjJ0J46bd3PGAx0vK+B4+sWzEnZ8HSUkjtHt+HnlaAPPxi+j7MgpSUoK27kMl9HyzAOqGjdx7RWoF5DMSocmuEdwz6PfD9ONhaGjRTKnFsJECnEkFcKUU3hsW/j9oDA6vvP/ACcEEDAaaoHfsDFhPXwqcc9y4Tz9sDgbc7pA7Px+t/zkb4pzakacF8EgU6BkXA9OOI5B8HQP9toOC667WLoi+XQDL+RuQxeRBQb4eALmqdtteiBPyoV60Cs6Hz2D/6RjM8bmwJ+fDmVoIc2rB/2MKuMFWn/P5qhXBCYZgPnke3V9Mh/XyLcF505FTEH8bKTj3d9CTtBC95Kufgrx4OTT1m+BuF0E8IRYWMvNQGH45h95p8ZDOTIJ7KB65/ngLeeEiyPKqYTx8EtZzV6Ata4BmQRb0CTkwJ+XBmloAW3rRTaYAM1t977dRGHR7BJPr9x3lhNev3yE4z6BZvQ3i2YkjT382lI2b0D12Psxnro68JICNonrP19Hce8upy+idFAu/wSi4R04ZSTKT0iVlKMe9J5DPS4E8PB3a2pWQR2ZAGU1xoawerruPMGCzw7JyI7kDKSCj0DKGVn+AC3qb9ggm1TXt5MxeMjlMcH4YUtKuJDZn5OnPhpJ8t29sOCRfRnDm+jGIGFd4xa+uMr8e0tRyOJ69JvcbWjCK/H0ksJwivWJuKlRhaVDRMfN745J1sJ++CL9Ki0Gfn4sJzuu3oU/LhyWzaGAMF/hmJwVSivvJH1DMT4H4y5mQUtCzn/l9+HcI0D03GYqCj/vwxyBOLoOmYjXUKZVQUd4eDT6VDt0U7Nx/tnLH9t9vQ/JdPHqnxqHfFYw/lit0fk4ylPNToSG/15Lw2uhMGEoWw7h4FbTpRVDHZ0OVVgh1dgk0qbkwZhaAU4C/uA7+h89hzq/h0pxx+SaYm49AOZU3vb+CaOJ8aFdsGXn6syGamQLDlp84t5NQpB9e4VCYrt1H+9dR6JkYC+P2g/B19UGduBCKaYlcxDft+wX9Zgt/M61fHy2Kfs02LkP5+qSw/nwa2rwK8v1saBJz6bPZMO5ohqetA6Z1m2EYVoB3VgIc4+fBOG4OHBd4n9SEpcK4bEPIz6GAQxMOW0oPpUDDlmbB9b+DTlpV7RJegTIiNbKYkhF3UKZ5/R5dE2IgoXuVUxKgmkppLiIHhqxaGArqofw+GbKEQgz4fNz9LOrL0j+cx/zrOcjjs6BMzIFuJS+T6+ETaAMKmJPEKcBz+xF30afUQEGW4BNLueMBhwO6rXvR9cVMqCqXw7h1H2T0Ofvpv3aPz0H72DDothzg3juf/Mnl+36LPXDdK1ehh9xESi6iq1kHXVoV9BG5MEQXwJRfBwsFUX1GBZRzUuAg62XoN5rRE5YC++OXgXmG4Xz1BpKELMgzCrhj95sWqDLzMIalP8/4+XAdDOZ/0w4S8JvwwLH96h0KiLMgHvs9KWYONNPjoRk3D15KN8NwtbRDf/JC4Phj6Lc70f7FfMrfwZTWOzEehuZfAsfKph/RMz8b3j4ZtAVLYF6yiYTeAseuI7Ct2gHbul3kw5XQzE+HYW0wS/WQucvrVweOQ2F/8Qp9SVRfmMzw9vZBmZnPK8D3w0+CGxXElFQZZYFjzcIlUE4nwkFfZMqugiVvEYwTImFZtzNwjySnGu//8/vA8cfgJGW1fxFGub0ncE6WtQiS1KrAse7gKUgza8hfu8jU02GlGGAsbOBc0HH8HPREeQ0kvI5qEnVSceBzijVb0RWVFjgeib7FS6FctwkeUoAiiyyAUd9+4vWhEE+JhOP6PbL9QWhSSqAcPxfaaaSAojrYsqph+zocVhrGyTGBFNYzKRKS+ELBPKNBf/QsOkgBLCUNQ7f9MLqnpQSO3W0idH9L5XBrBzRZNVDPSIZmVgpsR8/Atv84dDG5sO04AH1kFjSU6/0qDfc50/krEEVRedzaFpgrFF6VGt35JdAfOARlNsUA74T58F0MVlyDpGHx9FhoKM/rEillEN3VfjUXlupVcJ24AAvV+naq89kwkxK8LR3c5yRfzoOquDEwz8fQm16N7lnBQobBevMROsZFUW738icGByCaHEvudxcaqhvsF6m0piygiSukQXFg2WaqFK+QAjK5fO968Zr7mP3ZS3RHp6InNh09+WVQH/wZXjWvnGFIV6+HJJOyQm4hxjD/9/0e9MXB/n7IF+RwhQ4TXD9uLuxb9nLXzPmLYI7MgWV2KlkBU0AE3JSXfZ09UHxFQa2uKTDPx9D2RTj0e4U1B/N1lvLcnb2Bc91Uzxt+/Bl68ndt8RI4frtMubwQupSFMFYsh3nxGjiJ5GjJZa1n+DrF/oSYYwy5x8kzMP56Ft3JWWiPT4OovBaW53xwNF29DimZvza/kLcA/9M/4KBCx/rLWe4GZVIhDMQNmPDmELN2D5W+VorAbPWZAuwUkOyUj9VfhcOw+NMKcJFpt5MC+k1D+XsIfiq9OyZEw0mpbxjy2rWQU7zp1xnpxy6CrqCOOMpmmNZs54aZvS7fCFVsNtwt/Ods9x9TIEyH8SQvC3fu6QvIN+9AB0V9cW0DzDduQZ5bQMG1eEgB567CQFxAPYmnvbqSOujCSIukAA/FAi/9KFMI6bFu2w/duDAYiZB4X7VQbKDSdhwpoOqvo28oxGUr0RfDBy1VxVp4qeJjGPT3QzQ9GfaHwRTmoCzTSxmHER7j2h+gK26Arqiefjgpo7QBhhWboa1shCI6A/ab97jPmM9TvRCXDtXazYF5GAYpVnWmZUHRRIVVTy8UeWRJhaQAVgd46tfBuiAXOlbeanTwSeTQTqAgR4HPe/8ZDEkl0GZXBybTlDZCRTHASHmaMTlTXDH0M4jZ5Y5OaYfRTrzecvYGrDQk9F4evxCW365CQ9Yjpjl8xNmHYbl+nwouIjvfJ0GTUQ7r4VNwPXkJvz5YDA32+yGJIe5ft4I71h85gb6ETKiWrQ3c49Pp0ZGSSb6/jjv29PSQZZEFFJWwNBgOz2QyvYb1sK/cCt2kCAxYrDBQenGw3gBpTvPVPPik/EpxhcfYuXA+eklu0ghjRhXMxMwsy7cR9/54FrA9+oMiexKxsD8gH0/sbmIclJPioPgmHorJ8ZAT29Mv28oRMQYlBV4pKUAVX0DEJegaI9GXW47eGD6oarbshiQxC6qGldxxv92BzpRMiJfxxwyWW7epmMuHpqiYMcFwrqPrqljGXTSX1ENH5/REdAx03ly5Aro4nj0x6Lb/hJ6xc7j39nPXOd83xpXA864T6imJ6FcGV3Ak+uLL0Pt1DCe8moTXfpMAU+Zi2A/9BsvqnVBPTSK+kQT598Tmzl8n6loMxewUqKjC87by2eavoCez74rhc7+qcTXkmYXQ79hNbFKJ7rQcSJavEtyvOXAQkvwCaIqHFMC1tVdv5y6ai1jwmwcrCW5bsoHeE2NbHWRaZkqFthv3+QPiCbIvw6D8imeNyslxsJ64GLh3GOZbjyGan0P1QxRk42KhmhBHlrMIlkUbYMyh7yM3sFJh5CZ3Y5RXPYtWnXK+aeMemDc3Qz0/Db4e8chpA/DbbOii6s7dKYJqyUoYtu8ml2qENJ2y2ZDZh0JUuhCSAnKB0lKMGZwYQQogJRw5BX9HDxVE8yn4zcOgw8ndrJuZCNueo9x7AwU/WUJR6FzQrd1F5ewi7r2afrySqrWREJcupzoiEuJxMTCu2UP5XMxfYIVV/wBln/NQzU6Hlubxvm2HoWYtNHNSYWrcyAVcDQVkv3p0y2IQlVRD++MBKGuJNh86BmUGpblN/KKGwnDtBjpzciArobi2sHTYBcLhXrUdTqK2JlKAcWIkBq027gO69HKoo/NgOfob1QJzYWCt51HA4kLv2HD4NXrBeR3l/O4vI+F50x44Z2o+DkVikG4z6FZuh2JOGlyUbvUU8fXzM6CnWKSJIKanUAvuHQnpph1EsPKhLCiDvmE59ER2RsKr16M1Mwu6U6ehbFwCbdlCpoAIeCnXunJqYKcvtHxNfk8mOExTWSdFHpFFETsCJuLnnwJrXkjiSwXnRFPJpBcFOQIjPay1ZTp9OeQuHmrK83Li+M5Hz8k1CqgCzISWUd1PKEB34TJVj5lQpOeSaVfBuC1YpzB4NBq8LyhCew7fxVIto9RdTgroJwX0n7wId81qOInmMp5v/iaK650JEPIQ4mNwvGwhcye6/ICvLyxnrtHqR3HtqGGwdlhPWEgHdwR6v0+EfuU22IiY6SJ4qutXflwBFiI73UwBGZTOC0th/nF/4Jrj/Xtu5ZnwPUVF6He5YLl0EZryUsYDIuCZmcQJ7xhWAFmB/5/s9zOoVu2EaGwEXGTyPV9FQbdZWG12R+VRtfer4FwoVOt2QDo3hWtl6wsXQRP9aQU4RT0QpZACsvKhJZZn2dMM1+s30B48jM5cOnfiBKRr1qCvsIDIl4y4hA7qioWsGoyEj4Ice15nr1kDyzSqy4nl6eKL4A6hpX8X8sJlXNTvm54qOO+jNNk5LwOePrngfCiUTTshnp8C68lzcJyilYrJomDZP/I2ATxU5XWlZnMlrja/iJgixa6KKuIIebA+4Bs98lUrISkugvX2HXhlUigqShkVJhcY6qgwDBBxcFIFpg7P5Cq8XipzTcfOfrYLhEJetFRAbRlM1+6hk4LqaPCZzOgibq9dv4N8dAn0RHU1sRS4GtfBfPn6qB3kfgraXSS8nCxAQzTXfukyd6+svALW+3zaVm3fDklJEbHFI3C9b4WykhTgIQX4Lt8eMR0PJ/F8dX0TeugeEVmKnOKEuytYrf0zUP90Al3JwiAZCtXB4+imYsx49BTXz2fCaxNyoMleCCXR3dAeQij8Viu6cosgy86DhizAr+JdRpyfD3c333hR7tgOGQt+u3dRzXAGqqoyXgH+h8KGyAeg1TcdPYO+sCx0fjEPfSnEy4nc/DOwPHiOtll//UBl0OeD6eZ9OP5sQV94KrQ1y6FNK4I2Phs+2RAVHwX9djs6qcaX5uRBTUXOoNtNsWcLJFXBGkayYT10x45Cd/gQFHU10FSXMxeIhDO9Au4rd0OmGx1OIirSjGpSRBi6KJWZQ/p6n4vOlFJ0RWajPyTT+IwmvItIg3zLHrhFfVDUr6F0KeF6+RoanlE6PMNgriMqKiWOTxR3YRkMGzdDQf7u0wYJlIQsQHPyOGwvnkNO5q+tLWdBkO3YoBxP5awutRy28zc+GXAYPPQjlbVNXMoTfZcMXfOHT5RHg09vgii5BB1EcbtzKiHKrsR7WnFRUS38VIgNw3brHuSJOVDnlsFxjw9ko8EtlaGTfF9eWAQ1FTmM57ta+Ycpw5Dua4Z05w7O0qSVJdDUVjAeEEVMMAr28RTsvo6gyo+4/Zx0mPYf5wLLp8Ba0eo1uylGLEDn+Fhodh3BoEf4jHE0mK7dhWLTbii3NVOgejryMrTNhyiQVkNVtpj4xIc1RihcUik6MrMhpSJHW1VFAbQc3p5g05VBefIEREvquPf64z9DxSxgYGIM1QLRcNNwjI8iJhhFaZApIgKKKfEwNh8TTPIxsDZX54QYdNAc6i1BIvLPQr5xB2S1y4gdrodh/+GRlwVw9fWhPYs4fmEhmf9G6BoayD3PC+7RXLmMtkq+VnF1dUJRU8YsgFeAh7WjxjNLiIaNXs0khH5cFFRfRUK3bJtgoo+BdV50xCs6J0ajiyo6zd5gr//voqd6CVRNW6HdugsaemVgVmm4c4/rXYbCKRajPTsHUiI6pv37YNi6Bfp9fC9zGManT9FaVsQFdfvb15DWMCZIP9S37wT6Kbi5atZxwttICVZuxJBbREM7LhrmPZ9vCRyoylNv2YeOqXHopJrecCq4ueJz0RqTAv0vv8Jw9AQUi/l+hUehxNvEVDh7xYJ7PWo12nNzISkqhPXMb7CcPQPlGmGLziESoYUUwFKp430LJDUcE4zBQAjj81Fwc2zcRxYQwynANn4BvY8lJcTAE9Kx/TvQ7DyI9mkL0D4/lUtznwPjnQdoi02F5coN2O7ch7Rk6KHJQD9a07JgfhYkbww+iwXteXkc1bWQqTtfvYK0rlZA4PxmM96WFaLf6YKzqwPiWo4JxsBF1ZvryBlS41BPnuAmbmDilBBLSoij97EwlK8JXP+78FOaky5ag/ZZ8fTFqyg9CUvmULDn/m3JWRDFp8N8+hylQzH6slm7jRemo6AYuvPCoDhABU47Rf5eUoDtzh1yFSt6y0u48wGQMt4sLIBTIoGrtxt9TAHMAthmRSv5vHFGKvcIyi/hebrzHL9fz04KsI6Ph35y0ge7SP4uXB0idGeWoW1OApR7+IejofDpDRCV1qCLhBcnZcGway9HaftyCuAbesDRU7sY0g0jNk2RbjprqtFdmA/78+fcZ0SlpIzXfwpua6kqgeWPF5Q2JehbxMWAWAqAMRQAY8jUo7nAp6VhXfcjvK/bYJ6eThYQT0qIJyuIg7e1SzBhKNhDTzdVkawL+ymYrt5Ce0QyOpLy4BLx6Ur/+3W0xWdCFJcORWUdFKk5MO3eC3dbJ8QZObDee8DdJ9+8Dd0Ly0On4yBa2oguUoCzrY1bbVEZ5frfhFVn24oGaC5dgFsmgXhRGa8AH+Vw94RYEjKWVpwFvhgYuVc6/i6V0iPbP5AICynB87xFMCGD6eo9SKrXoPP7VHR+GwvRjERIsmu4wOfTCffzCMBWtmYp2iOT0ZNfgU7y+Z74DGhWNsGweQc0BWUwbtkB5+On3KMs3cEj3Md0J06iM/vD7Tk9TevQWZQPj5y34N4VSyDZLrSU7u1bID9yAC5xLySLOQUsgC+tBq6wfE4BLOgxv7fSK/N9tvKuoX26VlKE770oMJn95VtarWKixDHonbwA0u8SuN0bihlJUMxKhnxWEpW1VNBsaYZXOnr5a75xF705pWTyOdBv2QXridPQFlXAfv4SdHVL4X7zlityFIvrufutT55yCgjsERqCeOcPaCvKI7/n+5kKYn6dNcK2m/zUCfT9sBmO9lZI6spYDFiAAdar8/fDufMorLOzOeGZ37OVZxuVPROS6DUJ1qnpxPL4QGm7/gAi4hCstSUjwqSamgTdjGQYZqXCQJZgmJMG3dx0qOelQkFDPC8Fqk27BD8mFJofmqEsq4Xz3kNo80q43Rvc+7pGuJ69IJeopkInn7MaP9UQXZTynCOYnpgE7qgJuobh9k20UdALrSANz5+gu2klzI8ps9SXs2pwAfy/Cwshz80nsE5Lp1XnhecUMDEJtmp+e4mXgmQfuY70mzhu64p2WhKMMynFzUqDaTYNotLGeRkwhmXAQEMXkQFVRDp0u/+6oWp59pLzezPlfHVaLjSZ+dBmFZDgL6HfuBXW369Av3MPpLnk32/5vURdlPJMQ3X+MFTnzqK9piKQ+jwqJSkgX6Aot1qJrjVLoTv3K2QNFUwBtNKzMmBv2ALX2WtUFd6DfeshmKcw30+k2JBEIxl2UoBfztfY6oIGyEh41ZRE6Eh4E8se1Wu5vr6/TwrPm/ew7joMfWweDCQ8e4StKxrlsRn92PcU8aXE+mQp2bBfvw3bxctQZeXD8fAxTIeOwEjD/NtZrtLT7+fbayJKd5oTwgLM8vo1WopyucqSA5ubFT2XhDtXRBtWQbatCfIllYwHxHH785nfG1muH8deF3ABjymAmb6DhHce5/cDeXuk/Mp/Gw/dVF54+yh7ftkOLuvR09wGBn1t8NFUKFS/nEbbAgp+iZm0yvymK/e7Vsgz82C/eQd2UoJmw0aqDO9whY58Ic/lFZs2QdokbH37DAa8LaRs0RLcutO7bRO6NwWfEzKIm3ehe/FCKJgCfBMpsk9gwsZxQc9Mqc7C5f0EigOJsFHws28K5mvTfjKdyXHQfJcIw/QUmNOD21pGg3blZsijMuB88mHjpY18vSshA7IqvkpjMBPJEWflwvTraW6DlmJxHaw3b0NaVAQ51fjuzk4u1/dWV4TMxOqQQbwlC9BeCW7e0ly9hNYq4cMc1cWzEBEHCFEAC3bxXL5nhIetPhvWmDK4Tl8TfFi7dhdktPqc39PqOw+M3t0dhvHkOUij0iGLoXiwoxmOdzz1tr95h/a4NPQkZcInC2YJaW09JBT0FI3LuaAnr6+H+ew5qFavhqK6Crrt2+Gh6q+3qvyDXuW76oWQNAeDrZPK5JZyIlGmYDq2vnuLLlIA5wJMAd6Vu+DZcRT2SiqGqppg33wQ7rvPP5icQb3qB0iZAqYnw0gR33VGqKAPQFP05pRDEp0GxYJMyOIyoVrH7zVQbtvNrb7uYNCFDBd/R1d6NvqJ2/flEEnq6IRm124Yjv0C/YED0O3cSb9hBSn1JGQrl8GrFW5/EW3dgI4lwh2s76qIOt+6HjhmDZGuRsoqLAh6afX7H3y4r240aKjCY/leSynPSOnOspwvU0eD7sJVtIcTH4hJhzIuC4qELPiJ7jJ0J2ejJ1nY8m5Py4Ri+w/c+97SMhjIDZi5q5qa4HzzBppt22C9dBEy4vnS+lo4GOsLgeL0SbRS5A9F18ZV6N4q3L2iu3YJYj4NkvnXf1yIUFhuPoR4ajw0M1JgnE35PiwT/R8pbNyUFdQ//QxxagG3+po6Phj61FruUZZ8RTBAme8/QhspgD3tZZBv3ATZqlUY8PkhLiqAbi9xhcYGuCjIsaampKIEtlfCf6xYXr+ikjc/MAeDmuLAu1phJ1p7+Tz6GBFi/8qyTctA/4gHmqOBkYre74nUENMzEtlh+V6bWAzXy2Dk/SuwOsFw4je4WvkHpMZfz3CrbyGyM4z2jCwo9wcDrvbkr+jK51eTtbOlpUVQ1NfBdPoUcREJxYkSGK8Kd6sO+n14U5ZHiggqhinjbWUB7N3BOka0uoFXgGdCYr+Ncf29nw5mwzAcOwv5zCRo56bCOJ8nO6r5adA0UAx5JKzTR0NvaRX3KGu4M2y8fJVTQCjMjx6hPZfn/ObblAUWFlMc2A/lksVccFQ2rYFs84cbs1oWV0B5SsgRWhsq0b2Nv9fe8Z4LghQDBsZ4JyaZWL43zhB++aegKKyDak4q9MT1TRGZMBDZURPbk0VSsKtfDdszoWkKQD++PTEd3TnBLTWdJLyieV/ITSC+3oFWUsCAx8PV930Li6DZuR3qzRug27OTWOEbiOuCff9hdG5eR8Ly/yUahvT40UA6lDVv51Zf0VhppiyQfIExPSvFAtsm4UPMT0GzdCO38uwRtjEqC/roLGhjKMrHZkIaw3L7EhguXfugf+ehuv59El1fxRMZ3Qky9cwPnxazNte73Gw4OvjtMdLVKyCm4Ge5dRPy2nLoDuyDbO0K+C3CLXfy307ifYOQn3i0arRWF0N98igvPKVAZWPVZaoGk//DOymZ2B4VMpMoIN55Jvjgp2C7ehu64nruDwr62CwYFlBFF5/DPc1RJWRDkpCJngzi9SFbXGxvWtCanA7DOZ6idmflwHjpw53nnO/mZsH85Al3bKfg11tOQuzeAceff0BWQzm/vgqOljeCz1no+G1lPga8wQ4Xg/TAj+ghBsjyv3ZZNd5XF43l/jnm+yblnuubFFgnJ0M7mZQw9Gz/78B25Ta0JYuhHfpjkiEpD9qkXKiSc7hdW6EPPIx37uN9SgYcb1ugP3YcvXnBTVihGOwfIGqbT1Vd8A9bPbUV6KXo72p/D9P5s1xjU3VIaLn9TifeVBTA1hFMkawI6qF0KKHUp15aBe3ymgck+r/yCpic+g/PlFSbc0oKLFOSofk2AZZDp0Om/Hw47j+GYfl6aKi21ybnQZOSC/NpYX9ef/kaOtIo4jdthJiRna5gjyEUTAEtJUUwhlR9euIA3RXFkC6u5Giyes8OUkoJtx0uFO9opfV3ecWZXzxBBwU9tvrM9HXLa+yXspL+nUT/l6G/To4ZY/s2+f94pqaZ2B+RLdNSoKFCR51ZDcuFG/RFfIPh78BvNMNy+Dj0K9YLdocwGK/dQDd7ikP1veXK6P8aY88YWgvzBBbAIFm/ilt59bYNXEDVHjsM8foVFDOUgXuYufdtXQ/V8UNc4cP8npm+Zlm1ua26+P+SyP8tIPww+iYt+B+e6emP2b+wLTR0M1OgpHTH/pSoXrUNxtOXYL5+lx837sJ04x5MN+/BfIuN+7Dcvg/rnQewP3oKT1sn3K9b4Lh2E86nL2B78IjbqGB58JDbrirJYRuaiqjkfQgH+bjt8WOYHz+CKWQYKNh1lBRAun41rM+f0HhK9cMrqPfuhmwRBbK6chhP/Ezc4i1lgzJ015fBeO8WNGdPQrxxJXrpHDN5JriqsQqqpdVPm+bN+J9DwgdXfwT+xTg95SvH7IxbttnpFtOc9AEdpTuW8uRzU7itK2z3Rl9YCnrDaUSmojcqFX0xaRDHZkAclwEp+byCaK4ylWJAWh63b0eWkcf19SRZeZCxR9gkPNuqqi0pgaq4GDKq8vqKCtFdlA9RcQG6SwrRS2mPsT1ZZSlllIWQVpdyT3PkJLyqvgKaJeTLJJi6kSI6CckEZU0OxvHZq7KxckC9tNpKgt9urykeT7L99zEjhP//MOfXy8cfkiwAAAAASUVORK5CYII\\u003d",
   "modinfo":{
      "type":"FML",
      "modList":[
         
      ]
   }
}
```

**Comment by ldilley** [comment]
> If the official clients supports (or at least gracefully handles) this, we should probably too, right?

Agreed, sir.

**Comment by ldilley** [comment]
### Progress
- [ ] C#
- [x] Go (not applicable)
- [ ] Java
- [x] JavaScript (not applicable)
- [x] Perl (not applicable)
- [x] PHP (PR #217)
- [ ] PowerShell
- [x] Python (PR #217)
- [ ] Ruby
